### ISSUE TITLE
Have to double tap type tag before you can select it

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#118]
Feedback from a user: 

"When I type 'pla...' all items with the word 'pla' autopopulate (which is great) when I want to select the item I'm looking for it doesn't let me in the first try. I have to tap on it again before it selects it."

**Comment by munroTom** [comment]
@lizheard1 Is it possible to get a little more detail on this one?
I've tried it out on my phone and can't recreate it

**Comment by lizheard1** [comment]
@munroTom I've just tested on my phone and seems to be fixed - @neilfulwiler have you done this?

**Comment by neilfulwiler** [comment]
so I *think* this is a pretty difficult problem to solve so I'm going to focus on other things this week as the cost/benefit ratio here seems low. I agree its *very* annoying and I think I noticed this the first time actually but thought it was just me. the issue is (I think) that when the keyboard is open, and you touch a category, the touch doesn't go through, it instead just closes the keyboard. once the keyboard is closed, you can then touch the category and it works. So when the keyboard is open the touch events aren't propagating through to our elements. I have no idea how to fix that and googling is not helping. @munroTom any chance you know anything about this??

**Comment by lizheard1** [comment]
Right okay! That makes sense! In the older version of the app you could select items with the keyboard open (as you had to type and then suggestions came up in a drop down) and a double tap wasn't required - so perhaps there are some clues in the old code? Agree not the top priority right now, but does need fixing at some point as it is annoying for users

**Comment by munroTom** [comment]
I initially thought a similar thing to @neilfulwiler wrt to it being an issue with the touch events not propagating, but at least on my phone it seems to be working fine, if I type in an option and then select it (keyboard still open) it works, the input is filled with the option and my keyboard closes with one touch

This sort of issue could be super device or potentially even OS specific in trying to solve which makes it kind of hard to determine what the issue is

**Comment by neilfulwiler** [comment]
You’re android right? I buy that it’s iPhone specific. Happens to me though.

**Comment by munroTom** [comment]
Yeah, I've got an android, although I thought @lizheard1 had an iPhone? Although potentially if you're on different OS versions that could be why you don't see it

**Comment by lizheard1** [comment]
This is also causing issues in the labelling - e.g. people start to type out the category, click on the suggestion, but as they haven't doubled tapped, it doesn't work and is stored as the first few letters they typed. E.g. image below:

![image](https://user-images.githubusercontent.com/62663054/88454678-21ab8c00-ce69-11ea-8ba9-e3bf4f98136a.png)

@neilfulwiler to ask Joe's friend about this

**Comment by lizheard1** [comment]
![image](https://user-images.githubusercontent.com/62663054/88771379-1319e900-d177-11ea-8cf6-32c9ef2a86c1.png)
Lots of users are still doing this, so is an urgent thing to address
