### ISSUE TITLE
User not receiving confirmation email when they sign up

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#135]
A user downloaded the app and signed up a week ago, but has still not received an email to 'activate' her account and so can't take pics. She is called Katherine Rivers and has an iphone 10. Her email is katherine_rivers@hotmail.com

**Comment by munroTom** [comment]
Have you confirmed that the email isn't in their spam folder etc?

We don't have that much control over the emails being sent as google should just do that, can they resend the email from here?

<img width="625" alt="Screenshot 2020-06-27 at 11 56 20" src="https://user-images.githubusercontent.com/29929268/85920626-42ce8c00-b86d-11ea-9a70-4ecc6d26b7c9.png">

**Comment by munroTom** [comment]
This isn't the first time users have experienced this sort of issue, do we have a reason for forcing users to confirm their emails?

It seems to me like unnecessary friction for getting people using the app, especially if we expect people to be downloading it at a cleanup as it assumes people have email set up on their phone etc. (I know most people do)

We could just remove the verification step so that once they've signed up they can access their account straight away
