### ISSUE TITLE
Unable to see image to moderate - just see Plastic Patrol logo

### ISSUE THREAD

**Issue by lizheard1** [PlasticPatrol/PlasticPatrolWeb#155]
E.g. here:
![image](https://user-images.githubusercontent.com/62663054/88368325-b9d04500-cd85-11ea-997e-2d78ba4df5c8.png)
 There were a lot more, but they had 0 pieces and the location was the middle of the ocean, so I disapproved them - not sure what was happening?

These images in the screenshot, do have types and brands logged, but no image - how is this possible? E.g. below
![image](https://user-images.githubusercontent.com/62663054/88368399-e5ebc600-cd85-11ea-97ea-4c1b218fd483.png)

**Comment by munroTom** [comment]
I think this happens when people cancel the upload halfway through
We have to create a record in photos database so that we have the id for the photo to be stored in the bucket - if a user then cancels their upload halfway through we will have saved the `meta` information about that photo but not the actual image
When we fetch photos to moderate we get the most recent unmoderated entries from the database and then try to fetch the image afterwards - so you'll be able to see those cancelled uploads too

I think the main cause of this will be solved once we figure out the cause of uploads being slow but will still be an issue if people do want to cancel an upload for whatever reason, potentially we can do something in the app which also deletes the meta if an upload is cancelled

**Comment by lizheard1** [comment]
@lizheard1 to email users to see if they are having the above issue

**Comment by lizheard1** [comment]
I think the issue is that users are cancelling uploads halfway. Some of the logos (where there is no image) were from my account and I have had to do this as uploads have got stuck at 0% then I cancel them as it is taking too long. I have also emailed some users to corroborate this. @munroTom @neilfulwiler

**Comment by neilfulwiler** [comment]
Yeah @lizheard1 that sounds right. I'm hoping that https://github.com/PlasticPatrol/PlasticPatrolWeb/pull/166 will help here

**Comment by lizheard1** [comment]
@neilfulwiler @munroTom can I close this issue?
